name: angular2_mdc
version: 0.7.0-dev
author: Tobe O <thosakwe@gmail.com>
description: Angular2 Dart bindings for the Material Design Components Library.
homepage: https://github.com/thosakwe/material-components-ng2-dart
publish_to: none
environment:
  sdk: '>=1.22.0 <2.0.0'
dependencies:
  angular2: ^3.0.0-alpha
dev_dependencies:
  angular_test: '^1.0.0-alpha+6'
  test: ^0.12.6
transformers:
  - angular2
  - angular2/transform/codegen
  - angular2/transform/reflection_remover:
      $include:
          - test/directives/icon_test.dart
  - test/pub_serve:
      $include:
        - test/directives/**_test.dart