name: material_components_web
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
description: AngularDart bindings for the Material Design Components Library.
homepage: https://github.com/mdc-dart/material_components_web
publish_to: none
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  js: ^0.6.0
  mdc_web: ^0.4.0
  quiver: ^2.0.0
dev_dependencies:
  angular_router: ^2.0.0-alpha
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0